name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: j178/prek-action@v2

  test-top-level-build-testing:
    name: Top-level build testing [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, macos-15-intel, windows-latest]
    steps:
      - uses: actions/checkout@v6

      - name: Configure (PIXI_CMAKE_BUILD_TESTING=ON)
        run: cmake --log-level=DEBUG -S . -B build_top_level -DPIXI_CMAKE_BUILD_TESTING=ON

      - name: Build
        run: cmake --build build_top_level --verbose

      - name: Test
        run: ctest --test-dir build_top_level -C Debug --output-on-failure

